spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.zovqbblvdazsgbajtqny}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tickers&trades}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:never}
