spring.application.name=springboot_jdbc_01
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/demo1?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:demo1user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:demopass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
