CREATE TABLE IF NOT EXISTS admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fund_manager (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fund_manager_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customer_fund_manager
        FOREIGN KEY (fund_manager_id)
        REFERENCES fund_manager(id)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS portfolio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    portfolio_name VARCHAR(150) NOT NULL,
    total_investment NUMERIC(19, 4) NOT NULL DEFAULT 0,
    current_value NUMERIC(19, 4) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_portfolio_customer
        FOREIGN KEY (customer_id)
        REFERENCES customer(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    asset_type VARCHAR(30) NOT NULL,
    current_price NUMERIC(19, 4) NOT NULL DEFAULT 0,
    CONSTRAINT ck_asset_type
        CHECK (asset_type IN ('STOCK', 'MUTUAL_FUND', 'ETF'))
);

CREATE TABLE IF NOT EXISTS portfolio_holding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    quantity NUMERIC(19, 4) NOT NULL,
    average_buy_price NUMERIC(19, 4) NOT NULL,
    invested_amount NUMERIC(19, 4) NOT NULL,
    current_value NUMERIC(19, 4) NOT NULL,
    CONSTRAINT fk_holding_portfolio
        FOREIGN KEY (portfolio_id)
        REFERENCES portfolio(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_holding_asset
        FOREIGN KEY (asset_id)
        REFERENCES asset(id)
        ON DELETE RESTRICT,
    CONSTRAINT uk_portfolio_asset UNIQUE (portfolio_id, asset_id)
);

CREATE TABLE IF NOT EXISTS transaction_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    transaction_type VARCHAR(10) NOT NULL,
    quantity NUMERIC(19, 4) NOT NULL,
    price NUMERIC(19, 4) NOT NULL,
    transaction_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_transaction_portfolio
        FOREIGN KEY (portfolio_id)
        REFERENCES portfolio(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_transaction_asset
        FOREIGN KEY (asset_id)
        REFERENCES asset(id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_transaction_type
        CHECK (transaction_type IN ('BUY', 'SELL'))
);

CREATE TABLE IF NOT EXISTS benchmark (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    value NUMERIC(19, 4) NOT NULL,
    recorded_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_customer_fund_manager_id
    ON customer (fund_manager_id);

CREATE INDEX IF NOT EXISTS idx_portfolio_customer_id
    ON portfolio (customer_id);

CREATE INDEX IF NOT EXISTS idx_holding_portfolio_id
    ON portfolio_holding (portfolio_id);

CREATE INDEX IF NOT EXISTS idx_holding_asset_id
    ON portfolio_holding (asset_id);

CREATE INDEX IF NOT EXISTS idx_transaction_portfolio_id
    ON transaction_history (portfolio_id);

CREATE INDEX IF NOT EXISTS idx_transaction_asset_id
    ON transaction_history (asset_id);

CREATE INDEX IF NOT EXISTS idx_transaction_date
    ON transaction_history (transaction_date);

CREATE INDEX IF NOT EXISTS idx_benchmark_name_recorded_date
    ON benchmark (name, recorded_date);

CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    email VARCHAR(50)
);