create table if not exists admin (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    email varchar(150) not null unique,
    password varchar(255) not null,
    created_at timestamp not null default current_timestamp
);

create table if not exists fund_manager (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    email varchar(150) not null unique,
    phone varchar(30),
    created_at timestamp not null default current_timestamp
);

create table if not exists customer (
    id bigint generated by default as identity primary key,
    fund_manager_id bigint not null,
    name varchar(100) not null,
    email varchar(150) not null unique,
    phone varchar(30),
    created_at timestamp not null default current_timestamp,
    constraint fk_customer_fund_manager
        foreign key (fund_manager_id)
        references fund_manager(id)
        on delete cascade
);

create table if not exists portfolio (
    id bigint generated by default as identity primary key,
    customer_id bigint not null,
    portfolio_name varchar(120) not null,
    total_investment numeric(18,2) not null default 0,
    current_value numeric(18,2) not null default 0,
    created_at timestamp not null default current_timestamp,
    constraint fk_portfolio_customer
        foreign key (customer_id)
        references customer(id)
        on delete cascade
);

create table if not exists asset (
    id bigint generated by default as identity primary key,
    symbol varchar(30) not null,
    name varchar(150) not null,
    asset_type varchar(30) not null,
    current_price numeric(18,2) not null,
    constraint uq_asset_symbol unique (symbol)
);

create table if not exists portfolio_holding (
    id bigint generated by default as identity primary key,
    portfolio_id bigint not null,
    asset_id bigint not null,
    quantity numeric(18,4) not null,
    average_buy_price numeric(18,2) not null,
    invested_amount numeric(18,2) not null,
    current_value numeric(18,2) not null,
    constraint fk_holding_portfolio
        foreign key (portfolio_id)
        references portfolio(id)
        on delete cascade,
    constraint fk_holding_asset
        foreign key (asset_id)
        references asset(id),
    constraint uq_holding_portfolio_asset unique (portfolio_id, asset_id)
);

create table if not exists transaction_history (
    id bigint generated by default as identity primary key,
    portfolio_id bigint not null,
    asset_id bigint not null,
    transaction_type varchar(20) not null,
    quantity numeric(18,4) not null,
    price numeric(18,2) not null,
    transaction_date timestamp not null default current_timestamp,
    constraint fk_transaction_portfolio
        foreign key (portfolio_id)
        references portfolio(id)
        on delete cascade,
    constraint fk_transaction_asset
        foreign key (asset_id)
        references asset(id),
    constraint chk_transaction_type
        check (transaction_type in ('BUY', 'SELL'))
);

create table if not exists benchmark (
    id bigint generated by default as identity primary key,
    name varchar(50) not null,
    value numeric(18,2) not null,
    recorded_date timestamp not null default current_timestamp
);

create table if not exists accounts (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    email varchar(150) not null unique
);

create index if not exists idx_customer_fund_manager_id on customer(fund_manager_id);
create index if not exists idx_portfolio_customer_id on portfolio(customer_id);
create index if not exists idx_holding_portfolio_id on portfolio_holding(portfolio_id);
create index if not exists idx_holding_asset_id on portfolio_holding(asset_id);
create index if not exists idx_transaction_portfolio_id on transaction_history(portfolio_id);
create index if not exists idx_transaction_asset_id on transaction_history(asset_id);
create index if not exists idx_benchmark_name_recorded_date on benchmark(name, recorded_date);